common/models/DistributionCategory.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "distribution_category".
 *
 * @property int $id
 * @property string $name
 * @property int $city_id
 *
 * @property DistributionCity $city
 * @property DistributionFood[] $distributionFoods
 */
class DistributionCategory extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'distribution_category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['city_id'], 'integer'],
            [['name'], 'string', 'max' => 45],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => DistributionCity::className(), 'targetAttribute' => ['city_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'city_id' => 'City ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity()
    {
        return $this->hasOne(DistributionCity::className(), ['id' => 'city_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistributionFoods()
    {
        return $this->hasMany(DistributionFood::className(), ['category_id' => 'id']);
    }
}

backend/controllers/DistributionCategoryController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\DistributionCategory;
use common\models\DistributionCategorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DistributionCategoryController implements the CRUD actions for DistributionCategory model.
 */
class DistributionCategoryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all DistributionCategory models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DistributionCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DistributionCategory model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DistributionCategory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new DistributionCategory();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing DistributionCategory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing DistributionCategory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DistributionCategory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DistributionCategory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DistributionCategory::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/distribution-category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model common\models\DistributionCategory */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="distribution-category-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="box box-primary">
      <div class="box-header with-border">
        <label>Data Katergori Baru</label>
      </div>
      <div class="box-body">
        <div class="form-group col-md-12">
          <div class="col-md-2">
            <label>Nama Kategori</label>
          </div>
          <div class="col-md-5">
            <?= $form->field($model, 'name')->textInput(['maxlength' => true])->label(false) ?>
          </div>
        </div>
        <div class="form-group col-md-12">
          <div class="col-md-2">
            <label>Kota</label>
          </div>
          <div class="col-md-4">
            <?= $form->field($model, 'city_id')->dropDownList(
            ArrayHelper::map(\common\models\DistributionCity::find()->asArray()->all(), 'id', 'name'),['prompt'=>"Pilih Kota ..."]
            )->label(false) ?>
          </div>
        </div>

        <div class="form-group">
          <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>
      </div>
    </div>


    <?php ActiveForm::end(); ?>

</div>

backend/views/distribution-category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DistributionCategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="distribution-category-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'city_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/distribution-category/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\DistributionCategory */

$this->title = 'Create Distribution Category';
$this->params['breadcrumbs'][] = ['label' => 'Distribution Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="distribution-category-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/distribution-category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\DistributionCategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Distribution Categories';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="distribution-category-index">

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Distribution Category', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'name',
            [
              'label' => 'Nama Kategori',
              'attribute' => 'name',
            ],
            // 'city_id',
            [
              'label' => 'Kota',
              'attribute' => 'city_id',
              'value' => 'city.name',
              'filter'=>ArrayHelper::map(\common\models\DistributionCity::find()->asArray()->all(), 'id', 'name'),
            ],

            [
              'class' => 'yii\grid\ActionColumn',
              'header' => 'Actions',
              'headerOptions' => ['style' => 'color:#337ab7'],
              'template' => '{menu} {update} {delete}',
              'buttons' => [
                'menu' => function ($url, $model) {
                    return Html::a('<span class="btn btn-sm btn-warning"> MENU <i class="glyphicon glyphicon-cutlery"></i></span>', $url, [
                                'title' => Yii::t('app', 'Daftar Menu'),
                    ]);
                },

                'update' => function ($url, $model) {
                    return Html::a('<span class="btn btn-sm btn-success"><i class="glyphicon glyphicon-pencil"></i></span>', $url, [
                                'title' => Yii::t('app', 'Ubah'),
                    ]);
                },
                'delete' => function ($url, $model) {
                    return Html::a('<span class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i></span>', $url, [
                                'title' => Yii::t('app', 'Hapus'),
                                'data-confirm' => Yii::t('yii', 'Are you sure you want to delete?'),
                                'data-method' => 'post', 'data-pjax' => '0',

                    ]);
                },
              ],
              'urlCreator' => function ($action, $model, $key, $index) {
                if ($action === 'menu') {
                    $url = Url::to(['distribution-food/index','id'=>$model['id']]);
                    return $url;
                }
                if ($action === 'update') {
                    $url = Url::to(['distribution-category/update','id'=>$model['id']]);
                    return $url;
                }
                if ($action === 'delete') {
                    $url = Url::to(['distribution-category/delete','id'=>$model['id']]);
                    return $url;
                }

              }
          ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/distribution-category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\DistributionCategory */

$this->title = 'Update Distribution Category: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Distribution Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="distribution-category-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/distribution-category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\DistributionCategory */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Distribution Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="distribution-category-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'city_id',
        ],
    ]) ?>

</div>